name: Increment Version

outputs:
  version:
    description: "New version"
    value: ${{ steps.project.outputs.version }}
  previous:
    description: "Old version"
    value: ${{ steps.project.outputs.previous }}

runs:
  using: composite

  steps:
    - name: 'Increment version'
      id: project
      shell: sh
      run: ${GITHUB_ACTION_PATH}/increment-version.sh
